[project]
name = "langchain-tour"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "docarray>=0.41.0",
    "langchain>=1.4.0",
    "langchain-classic>=1.0.8",
    "langchain-community>=0.4.2",
    "langchain-core>=1.6.2",
    "langchain-experimental>=0.4.2",
    "langchain-ollama>=1.1.0",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
