# Default setting values for

# LLM overall
model:
  name: "gemma3:12b"
  temperature: 0.0
  top_k: 64
  top_p: 0.95
  context_length: 32000

# Continuous conversation memory
memory:
  type: "window" # available: 'buffer', 'window', 'token', 'summary'
  window_size: 3 # for 'window' memory type
  max_token_limit: 100 # for 'token' & 'summary' memory types
  verbose: False

# Prompting overall
prompts:
  one_shot: "what is 1+1?"
  system: >
    Be professional, concise and to the point.
  default: >
    Translate the text that is delimited by triple backticks 
    into a style that is {style}.
    text: ```{text}```
  translate: >
    Translate the text that is delimited by triple backticks 
    into a style that is {style}. Do not add any explanations or
    additional information. Just return the translated text.
    text: ```{text}```
  extract: >
    For the following text, extract the following information:
    {format_instructions}
    text: {text}
  rag: >
    You are a helpful assistant.
    Here is the conversation history: {history}
    Here are the top search results: {search_results}
    User question: {user_input}
    Answer:
  agent:
    math: "What are the roots of x in x**2 + 2x + 4?"
    wikipedia: >
      Tom M. Mitchell is an American computer scientist
      and the Founders University Professor at Carnegie Mellon University (CMU)
      what book did he write?
    code:
      prompt: >
        Sort these customers by last name and then first name 
        and print the output: {customer_list}
      content:
        - first_name: Harrison
          last_name: Chase
        - first_name: Lang
          last_name: Chain
        - first_name: Dolly
          last_name: Too
        - first_name: Elle
          last_name: Elem
        - first_name: Geoff
          last_name: Fusion
        - first_name: Trance
          last_name: Former
        - first_name: Jen
          last_name: Ayai
    time: >
      Returns todays date, use this for any
      questions related to knowing todays date.
      The input should always be an empty string,
      and this function will always return todays
      date - any date mathmatics should occur
      outside this function.
  eval:
    pockets:
      query: "Do the Cozy Comfort Pullover Set have side pockets?"
      answer: "Yes"
    collection:
      query: "What collection is the Ultra-Lofty 850 Stretch Down Hooded Jacket from?"
      answer: "The DownTek collection"

# Example applications
examples:
  translate:
    - name: "pirate"
      source: |
        Arrr, I be fuming that me blender lid
        flew off and splattered me kitchen walls
        with smoothie! And to make matters worse,
        the warranty don't cover the cost of
        cleaning up me kitchen. I need yer help
        right now, matey!
      style: "American English in a calm and respectful tone"
    - name: "customer"
      source: |
        Hey there customer,
        the warranty does not cover
        cleaning expenses for your kitchen
        because it's your fault that
        you misused your blender
        by forgetting to put the lid on before
        starting the blender.
        Tough luck! See ya!
      style: "a polite tone that speaks in English Pirate"
  extract:
    - name: "product_review"
      source: |
        This leaf blower is pretty amazing. It has four settings:
        candle blower, gentle breeze, windy city, and tornado.
        It arrived in two days, just in time for my wife's
        anniversary present.
        I think my wife liked it so much she was speechless.
        So far I've been the only one using it, and I've been
        using it every other morning to clear the leaves on our lawn.
        It's slightly more expensive than the other leaf blowers
        out there, but I think it's worth it for the extra features.
      schema: "product_review"

# Schemas defintion for extraction and other specific tasks
schemas:
  product_review:
    - name: "gift"
      description: >
        Was the item purchased as a gift for someone else?
        Answer True if yes, False if not or unknown.
    - name: "delivery_days"
      description: >
        How many days did it take for the product
        to arrive? If this information is not found, output -1.
    - name: "price_value"
      description: >
        Extract any sentences about the value or price,
        and output them as a comma separated Python list.

# RAG (Retrieval Augmented Generation)
rag:
  filepath: "../data/clothing.csv"
  embedding_model: "nomic-embed-text"